config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'categories#index'

  get 'search' => 'links#search', as: :links_search

  devise_for :users

  admin_constraint = ->(request) { request.env['warden'].authenticate? && request.env['warden'].user.is_admin }
  constraints admin_constraint do
    mount Sidekiq::Web, at: '/sidekiq', as: :background_tasks_dashboard
  end
  get 'links/recent' => 'links#recent', as: :recent_links
  get 'links/no_titles' => 'links#links_without_titles', as: :links_without_titles
  post 'links/fetch_missing_titles' => 'links#fetch_missing_titles', as: :fetch_missing_titles

  get 'reading_list' => 'saved_links#index', as: :reading_list
  post 'saved_link/:link_id' => 'saved_links#create', as: :save_link
  delete 'saved_link/:link_id' => 'saved_links#delete', as: :delete_saved_link

  get 'import_links' => 'link_import#new', as: :import_links_form
  post 'import_links' => 'link_import#import', as: :import_links

  post 'categories/reorder' => 'categories#reorder', as: :reorder_categories
  resources :categories do
    post 'reorder_subcategories'
    resources :subcategories, shallow: true do
      post 'reorder_links'
      resources :links do
        member do
          post 'upvote'
          post 'downvote'
          post 'unvote'
        end
      end
    end
  end

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  include BaseCategory
  belongs_to :category
  has_many :links, dependent: :destroy

  has_one :category_subcategory_position, dependent: :destroy

  validates :category, presence: true

  def to_s
    name
  end

  def ordered_links order = :asc
    fail InvalidArgument.new('Invalid order') unless %i(asc desc).include?(order)

    links.joins("LEFT JOIN category_subcategory_link_positions
ON category_subcategory_link_positions.link_id = links.id")
      .order("category_subcategory_link_positions.position #{order}")
  end

  def set_link_order links_array
    links_array.each_index do |index|
      link = links_array[index]
      position = index + 1

      CategorySubcategoryLinkPosition
        .where(category: self.category, subcategory: self, link: link)
        .first_or_create
        .update(position: position)
    end

  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  layout 'with_categories_header'

  before_action :find_category, only: %i(new create)
  before_action :find_subcategory, only: %i(show reorder_links destroy edit update)
  before_action :make_sure_admin_signed_in, except: %i(show)

  def new
    @subcategory = @category.subcategories.new
  end

  def create
    @subcategory = @category.subcategories.create subcategory_params

    if @subcategory.valid?
      flash[:notice] = "Subcategory #{@subcategory.name} was created"
      redirect_to @category
    else
      flash_messages_from_errors(@subcategory.errors)
      redirect_to :back
    end
  end

  def destroy
    if @subcategory.destroy
      flash[:notice] = 'Subcategory was successfully deleted'
    else
      flash[:alert] = 'Could not delete subcategory'
    end
    redirect_to :back
  end

  def show
  end

  def reorder_links
    links_ids = params[:link_ids]

    respond_to do |format|
      format.json do
        links_array = links_ids
          .reject(&:empty?)
          .map(&:to_i)
          .map { |id| Link.find(id) }

        render :json => { success: @subcategory.set_link_order(links_array) }
      end
    end
  end

  def edit
  end

  def update
    @subcategory.update(subcategory_params)
    if @subcategory.valid?
      flash[:notice] = "Subcategory '#{@subcategory.name}' was successfully updated"
      redirect_to @subcategory.category
    else
      flash_messages_from_errors(@subcategory.errors)
      redirect_to :back
    end
  end

  private

  def find_subcategory
    @subcategory ||= Subcategory.find(params[:id] || params[:subcategory_id])
  end

  def find_category
    @category ||= Category.find(params[:category_id])
  end

  def subcategory_params
    params.require(:subcategory).permit(:name)
  end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
  def subcategories(category)
    @subcategories ||= category.ordered_subcategories
  end

  def edit_subcategory_dropdown(subcategory)
    if admin_signed_in?
      menu_items = [['Edit subcategory', edit_subcategory_path(subcategory)],
                    ['Delete subcategory', subcategory_path(subcategory), {
                       'data-confirm' => 'Are you sure you want to delete this subcategory?',
                       method: :delete }],
                    :separator,
                    ['New link', new_subcategory_link_path(subcategory)]]

      menu_button 'Edit subcategory', :xs, menu_items
    end
  end
end

app/views/subcategories/_form.html.haml
= set_title title
.col-md-6
  = bootstrap_form_for [@subcategory.category, @subcategory], html: { role: 'form'} do |f|
    = f.text_field :name, id: 'name'
    = f.submit button_text

app/views/subcategories/_subcategory.html.haml
.subcategory-list-item{'data-subcategory-id' => subcategory.id, id: "subcategory-#{subcategory.id}", 'data-reorder-links-path' => subcategory_reorder_links_path(subcategory)}
  .thumbnail.subcategory-box
    - if admin_signed_in?
      .subcategory-handle
    .caption
      %h3.category-title
        = link_to subcategory, class: 'subcategory-title' do
          = subcategory
          %small.category-more-caption (more)
        = edit_subcategory_dropdown(subcategory)
      .list-group.link-list.clearfix
        - subcategory.ordered_links.each do |link|
          - if defined?(detailed) && detailed
            = render_link link, type: :medium, buttons: true, category: true
          - else
            = render_link link, type: :medium, buttons: true

app/views/subcategories/edit.html.haml
= render partial: 'form', locals: {title: "Edit subcategory '#{@subcategory.name}'", button_text: 'Save', category: @category, subcategory: @subcategory}

app/views/subcategories/new.html.haml
= render partial: 'form', locals: {title: 'New Subcategory', button_text: 'Create', category: @category, subcategory: @subcategory}

app/views/subcategories/show.html.haml
.col-md-10
  .subcategories-list.sortable
    = render partial: 'subcategories/subcategory', locals: { subcategory: @subcategory, detailed: true }