config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'categories#index'

  get 'search' => 'links#search', as: :links_search

  devise_for :users

  admin_constraint = ->(request) { request.env['warden'].authenticate? && request.env['warden'].user.is_admin }
  constraints admin_constraint do
    mount Sidekiq::Web, at: '/sidekiq', as: :background_tasks_dashboard
  end
  get 'links/recent' => 'links#recent', as: :recent_links
  get 'links/no_titles' => 'links#links_without_titles', as: :links_without_titles
  post 'links/fetch_missing_titles' => 'links#fetch_missing_titles', as: :fetch_missing_titles

  get 'reading_list' => 'saved_links#index', as: :reading_list
  post 'saved_link/:link_id' => 'saved_links#create', as: :save_link
  delete 'saved_link/:link_id' => 'saved_links#delete', as: :delete_saved_link

  get 'import_links' => 'link_import#new', as: :import_links_form
  post 'import_links' => 'link_import#import', as: :import_links

  post 'categories/reorder' => 'categories#reorder', as: :reorder_categories
  resources :categories do
    post 'reorder_subcategories'
    resources :subcategories, shallow: true do
      post 'reorder_links'
      resources :links do
        member do
          post 'upvote'
          post 'downvote'
          post 'unvote'
        end
      end
    end
  end

end

app/models/link.rb
require 'title_fetcher'

class Link < ActiveRecord::Base
  validates :url, presence: true, allow_blank: false
  validates :url, uniqueness: { scope: %i(subcategory_id) }

  validates :subcategory_id, presence: true

  validate :validate_url_format

  belongs_to :subcategory

  has_one :promo_announcement, dependent: :destroy
  accepts_nested_attributes_for :promo_announcement, reject_if: ->(attributes) { !attributes[:is_visible] && attributes[:message].empty? }

  before_validation :fix_url

  after_save :async_fetch_title_and_save

  scope :no_title, -> { where("title is null or title = ''") }

  default_scope -> { order(score: :desc) }

  acts_as_taggable
  acts_as_votable

  def category
    subcategory.category
  end

  def hostname
    URI(url).hostname
  end

  def fix_url
    self.url = self.class.fix_url url
  end

  def validate_url_format
    unless url =~ /^#{URI.regexp(['http', 'https'])}$/
      errors.add(:url_format, 'is invalid')
    end
  end

  def async_fetch_title_and_save
    return if self.title

    TitleFetcherWorker.perform_async(self.id)
  end

  def to_s
    return title unless title.nil? || title.empty?
    return hostname
  end

  def truncated_title how_much
    return to_s unless how_much
    to_s.truncate how_much
  end

  def self.fetch_missing_titles
    ids_to_fetch = no_title.pluck(:id)
    ids_to_fetch.each { |id| TitleFetcherWorker.perform_async(id) }
    return ids_to_fetch.count
  end

  def upvote_by user
    vote_up user
    update_score
  end

  def downvote_by user
    vote_down user
    update_score
  end

  def update_score
    self.score = weighted_score
    save
  end

  def score
    value = read_attribute(:score)
    return value if value
    update_score
    read_attribute(:score)
  end

  def self.fix_url url
    if url =~ /:\/\// # no protocol
      return url
    else
      if url =~ /\A[\w\.]+\.[\w]+[\w\/\?\&\=\%]+\Z/
        # ^ seems like a valid url with protocol missing
        return 'http://' + url # add protocol
      else
        url
      end
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  include ActionView::Helpers::TextHelper

  layout 'with_categories_header'

  before_action :find_subcategory, only: %i(new create)
  before_action :find_link, only: %i(edit update destroy upvote downvote)
  before_action :make_sure_admin_signed_in, only: %i(new create destroy edit update links_without_titles recent fetch_missing_titles)
  before_action :make_sure_user_can_vote, only: %i(upvote downvote unvote)

  def search
    query = params[:q]
    if query.empty?
      flash[:alert] = 'Search query is empty'
      redirect_to root_path
    end

    tags_query = query.gsub(/\s+/, ' ').split(' ')

    @links = Link.tagged_with(tags_query, any: true, wild: true)
  end

  def new
    @link = @subcategory.links.new
    @link.build_promo_announcement
  end

  def create
    # we can't create it with promo announcement in one step because
    # promo_announcement has to have a link_id which is not created yet
    @link = @subcategory.links.create link_params.except('promo_announcement_attributes')
    @link.update link_params

    if @link.valid?
      flash[:notice] = "Link was created"
      redirect_to @subcategory.category
    else
      flash_messages_from_errors(@link.errors)
      redirect_to :back
    end
  end

  def destroy
    if @link.destroy
      flash[:notice] = "Link was successfully deleted"
    else
      flash[:alert] = "Could not delete link"
    end

    redirect_to :back
  end

  def edit
    @link.build_promo_announcement unless @link.promo_announcement
  end

  def update
    @link.update(link_params)

    if @link.valid?
      flash[:notice] = "Link was updated successfully"
      redirect_to @link.category
    else
      flash_messages_from_errors(@link.errors)
      redirect_to :back
    end
  end

  def upvote
    @link.upvote_by(current_user)
    redirect_to :back
  end

  def downvote
    @link.downvote_by(current_user)
    redirect_to :back
  end

  def unvote
    @link.unvote_by(current_user)
    redirect_to :back
  end

  def recent
    @links = Link.order(updated_at: :desc).take(50)
    render layout: 'with_header'
  end

  def links_without_titles
    @links = Link.no_title.all
  end

  def fetch_missing_titles
    count = Link.fetch_missing_titles
    flash[:notice] = "Fetching #{pluralize(count, 'missing title')}"
    redirect_to :back
  end

  private

  def find_link
    @link ||= Link.find(params[:id])
  end

  def find_subcategory
    @subcategory ||= Subcategory.find(params[:subcategory_id])
  end

  def link_params
    params.require(:link).permit(:url, :title, :tag_list, :author, :description, promo_announcement_attributes: %i(id link_id is_visible message))
  end

  def make_sure_user_can_vote
    unless user_signed_in?
      flash[:alert] = "Please sign in to vote"
      redirect_to :back
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
  def edit_link_button link
    if admin_signed_in?
      menu_items = [['Edit link', edit_link_path(link)],
                    ['Delete link', link_path(link), {
                       'data-confirm' => 'Are you sure you want to delete this link?',
                       method: :delete }],
                   ]

      menu_button 'Edit', :xs, menu_items
    end
  end

  def share_link_url link
    "mailto:?subject=Check out this website!&body=#{link} - #{link.url}"
  end
end

app/views/links/_big_vote_buttons.html.haml
.vote_buttons
  = link_to upvote_link_path(link), method: :post do
    = glyphicon 'arrow-up'
  .link-votes= link.score
  = link_to downvote_link_path(link), method: :post do
    = glyphicon 'arrow-down'

app/views/links/_link.html.haml
%span
  %a{href: link.url, target: '_blank'}= link.truncated_title(truncate_title)
  - if buttons || edit_button
    = edit_link_button(link)
  - if buttons || vote_buttons
    %span.link-buttons
      = render partial: 'links/votes', locals: { link: link }
      = render partial: 'links/link_buttons', locals: { link: link }
  - if buttons || share_button
    %a.share-button{href: share_link_url(link), title: 'Share via email'}
      = glyphicon 'share'

app/views/links/_link_buttons.html.haml
%span.link-buttons
  = render partial: 'links/reading_list_button', locals: { link: link }
  = render partial: 'links/vote_buttons', locals: { link: link }

app/views/links/_link_category.html.haml
.link-category
  = link_to link.category, category_path(link.category), class: 'link-category'
  = '/'
  = link_to link.subcategory, subcategory_path(link.subcategory), class: 'link-category'

app/views/links/_link_list.html.haml
%table.table.table-striped
  %thead
    %th Link
    %th Category
    %th Subcategory
    %th Last updated (or created)
    %th Tags
  %tbody
    - unless links.nil?
      - links.each do |link|
        %tr
          %td= render_link link
          %td= link_to link.category, link.category
          %td= link_to link.subcategory, link.subcategory
          %td= time_ago_in_words(link.updated_at) + ' ago'
          %td= link.tag_list

app/views/links/_medium_link.html.haml
%div.clearfix.link-list-item{'data-link-id' => link.id}
  - if admin_signed_in?
    .link-handle
  = render partial: 'links/big_vote_buttons', locals: { link: link }
  .link-description.link-group-item
    %h4.link-title
      = render partial: 'links/reading_list_button', locals: { link: link }
      %a.link-group-item-header{href: link.url, target: '_blank'}
        = link.truncated_title(truncate_title)
        - if author
          %small= "#{link.author}" if link.author
    = edit_link_button(link)
    - if category
      %strong
        = render partial: 'links/link_category', locals: { link: link }
    - if link.description
      %p= link.description
    - if tags
      .link-tags= link.tag_list.empty? ? 'No tags' : link.tag_list.first(10).join(', ')
    %a.share-link{href: share_link_url(link)}
      share

  .clear-left

app/views/links/_reading_list_button.html.haml
- if user_signed_in?
  - if current_user.has_link?(link)
    = link_to delete_saved_link_path(link), method: :delete, class: 'link-star' do
      = glyphicon 'star'
  - else
    = link_to save_link_path(link), method: :post, class: 'link-star-empty' do
      = glyphicon 'star-empty'

app/views/links/_vote_buttons.html.haml
- if user_signed_in?
  = link_to upvote_link_path(link), method: :post do
    %span.glyphicon.glyphicon-arrow-up
  = link_to downvote_link_path(link), method: :post do
    %span.glyphicon.glyphicon-arrow-down

app/views/links/_votes.html.haml
- unless link.score == 0
  %span.link-votes
    = "(#{link.score})"

app/views/links/edit.html.haml
= render partial: 'form', locals: {title: 'Edit Link', button_text: 'Save', link: @link}

app/views/links/links_without_titles.html.haml
= set_title "#{pluralize(@links.count, 'link')} have no #{@links.count > 1 ? 'titles' : 'title'}"

= form_tag fetch_missing_titles_path do
  %button.btn.btn-default{type: 'submit'}
    Fetch missing titles


= render partial: 'link_list', locals: { links: @links }

app/views/links/new.html.haml
= render partial: 'form', locals: {title: 'New Link', button_text: 'Create', subcategory: @subcategory, link: @link}

app/views/links/recent.html.haml
= set_title 'Recently updated links'

= render partial: 'link_list', locals: { links: @links }

app/views/links/search.html.haml
- @links.each do |link|
  = render_link link, type: :medium, buttons: false, category: true