config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'categories#index'

  get 'search' => 'links#search', as: :links_search

  devise_for :users

  admin_constraint = ->(request) { request.env['warden'].authenticate? && request.env['warden'].user.is_admin }
  constraints admin_constraint do
    mount Sidekiq::Web, at: '/sidekiq', as: :background_tasks_dashboard
  end
  get 'links/recent' => 'links#recent', as: :recent_links
  get 'links/no_titles' => 'links#links_without_titles', as: :links_without_titles
  post 'links/fetch_missing_titles' => 'links#fetch_missing_titles', as: :fetch_missing_titles

  get 'reading_list' => 'saved_links#index', as: :reading_list
  post 'saved_link/:link_id' => 'saved_links#create', as: :save_link
  delete 'saved_link/:link_id' => 'saved_links#delete', as: :delete_saved_link

  get 'import_links' => 'link_import#new', as: :import_links_form
  post 'import_links' => 'link_import#import', as: :import_links

  post 'categories/reorder' => 'categories#reorder', as: :reorder_categories
  resources :categories do
    post 'reorder_subcategories'
    resources :subcategories, shallow: true do
      post 'reorder_links'
      resources :links do
        member do
          post 'upvote'
          post 'downvote'
          post 'unvote'
        end
      end
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  include BaseCategory

  has_many :subcategories, dependent: :destroy
  has_many :links, through: :subcategories, dependent: :destroy

  has_one :category_position, dependent: :destroy

  validates :name, uniqueness: true

  scope :displayed, -> { where("hidden is null or hidden != 't'") }

  def self.ordered order = :asc
    fail InvalidArgument.new('Invalid order') unless %i(asc desc).include?(order)

    Category.joins("LEFT JOIN category_positions
ON category_positions.category_id = categories.id")
      .order("category_positions.position #{order}")
  end

  def self.set_order categories_array
    categories_array.each_index do |index|
      category = categories_array[index]
      position = index + 1
      CategoryPosition.where(category: category)
        .first_or_create
        .update(position: position)
    end

  end

  def ordered_subcategories order = :asc
    fail InvalidArgument.new('Invalid order') unless %i(asc desc).include?(order)

    subcategories.joins("LEFT JOIN category_subcategory_positions
ON category_subcategory_positions.subcategory_id = subcategories.id")
      .order("category_subcategory_positions.position #{order}")
  end

  def set_subcategory_order subcategories_array
    subcategories_array.each_index do |index|
      subcategory = subcategories_array[index]
      position = index + 1

      CategorySubcategoryPosition
        .where(category: self, subcategory: subcategory)
        .first_or_create
        .update(position: position)
    end
  end

  def to_s
    name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'with_categories_header'

  before_action :make_sure_admin_signed_in, only: %i(new create destroy edit update)
  before_action :make_sure_user_signed_in, only: %i(reorder reorder_subcategories)
  before_action :find_category, except: %i(index new create reorder)

  before_action :find_promo_announcement, only: %i(index)

  def index
    gon.push({reorder_categories_path: reorder_categories_path})
  end

  def show
    gon.push({reorder_subcategories_path: category_reorder_subcategories_path(@category)})
  end

  def new
    @category = Category.new
    render layout: 'with_header'
  end

  def create
    @category = Category.create category_params
    redirect_to_resource_if_valid @category
  end

  def destroy
    if @category.destroy
      flash[:notice] = 'Category was successfully deleted'
    else
      flash[:alert] = 'Could not delete category'
    end

    redirect_to categories_path
  end

  def edit
  end

  def update
    @category.update(category_params)
    redirect_to_resource_if_valid @category
  end

  def move
    position = params[:position]

    current_user.move_category(@category, position)
  end

  def reorder
    category_ids = params[:category_ids]

    respond_to do |format|
      format.json do
        categories_array = category_ids
          .reject(&:empty?)
          .map(&:to_i)
          .map { |id| Category.find(id) }

        render :json => { success: Category.set_order(categories_array) }
      end
    end
  end

  def reorder_subcategories
    subcategory_ids = params[:subcategory_ids]

    respond_to do |format|
      format.json do
        subcategories_array = subcategory_ids
          .reject(&:empty?)
          .map(&:to_i)
          .map { |id| @category.subcategories.find(id) }

        render :json => { success: @category.set_subcategory_order(subcategories_array) }
      end
    end
  end

  private

  def find_category
    id = params[:id] || params[:category_id]
    @category = Category.find(id)
  end

  def category_params
    params.require(:category).permit(:name, :hidden)
  end

  def make_sure_user_signed_in
    unless user_signed_in?
      flash[:alert] = 'You have to sign in to use this feature'
      redirect_to :back
    end
  end

  def find_promo_announcement
    @promo_announcement = PromoAnnouncement.active
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def categories
    if admin_signed_in?
      @categories ||= Category.ordered
    else
      @categories ||= Category.displayed.ordered
    end
  end

  def current_category
    return @category if defined?(@category)
    nil
  end

  def current_category? category
    current_category == category
  end

  def edit_category_dropdown
    if admin_signed_in?
      menu_items = [['Edit category', edit_category_path(@category)],
                    ['Delete category', category_path(@category), {
                       'data-confirm' => 'Are you sure you want to delete this category?',
                       method: :delete }],
                    :separator,
                    ['New subcategory', new_category_subcategory_path(@category)]]

      menu_button 'Edit category', :small, menu_items
    end
  end
end

app/views/categories/_category.html.haml
.col-lg-4.col-md-4.col-sm-6.col-xs-12.category-grid-item{id: "category-#{category.id}", 'data-category-id' => category.id}
  - if admin_signed_in?
    .category-handle
  .thumbnail.category-box
    .caption
      %h3.category-title
        = link_to category, class: (category.hidden ? 'hidden-category' : '') do
          = category
      %p
        %ul.links-list
          - category.links.order(created_at: :desc).first(5).each do |link|
            %li
              = render_link link, buttons: false
      = link_to category, class: (category.hidden ? 'hidden-category' : '') do
        .category-more-caption (more)

app/views/categories/_form.html.haml
= set_title title
.col-md-6
  = bootstrap_form_for category, html: { role: 'form'} do |f|
    = f.text_field :name, id: 'name'
    = f.check_box :hidden
    = f.submit button_text

app/views/categories/edit.html.haml
= render partial: 'form', locals: {title: 'Edit category', button_text: 'Save', category: @category}

app/views/categories/index.html.haml
- if @promo_announcement
  = render @promo_announcement
- if admin_signed_in?
  .row
    .col-md-3
      %h4
        = link_to 'New Category', new_category_path, class: 'btn btn-default'

.categories-grid.sortable
  - categories.each do |category|
    = render category

app/views/categories/new.html.haml
= render partial: 'form', locals: {title: 'New category', button_text: 'Create', category: @category}

app/views/categories/show.html.haml
.col-md-10
  - set_title @category.name do |title|
    %h1
      = title
      = edit_category_dropdown


  .subcategories-list.sortable
    - subcategories(@category).each do |subcategory|
      = render subcategory