config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'categories#index'

  get 'search' => 'links#search', as: :links_search

  devise_for :users

  admin_constraint = ->(request) { request.env['warden'].authenticate? && request.env['warden'].user.is_admin }
  constraints admin_constraint do
    mount Sidekiq::Web, at: '/sidekiq', as: :background_tasks_dashboard
  end
  get 'links/recent' => 'links#recent', as: :recent_links
  get 'links/no_titles' => 'links#links_without_titles', as: :links_without_titles
  post 'links/fetch_missing_titles' => 'links#fetch_missing_titles', as: :fetch_missing_titles

  get 'reading_list' => 'saved_links#index', as: :reading_list
  post 'saved_link/:link_id' => 'saved_links#create', as: :save_link
  delete 'saved_link/:link_id' => 'saved_links#delete', as: :delete_saved_link

  get 'import_links' => 'link_import#new', as: :import_links_form
  post 'import_links' => 'link_import#import', as: :import_links

  post 'categories/reorder' => 'categories#reorder', as: :reorder_categories
  resources :categories do
    post 'reorder_subcategories'
    resources :subcategories, shallow: true do
      post 'reorder_links'
      resources :links do
        member do
          post 'upvote'
          post 'downvote'
          post 'unvote'
        end
      end
    end
  end

end

app/helpers/layout_helper.rb
module LayoutHelper
  def menu_button title, size = nil, items
    button_class = case size
                   when :large then 'btn-lg'
                   when :small then 'btn-sm'
                   when :xs then 'btn-xs'
                   else ''
                   end

    menu_items = items.map do |item|
      if item.kind_of?(Array)
        item_hash = {
          title: item.first,
          url: item.second,
        }

        if item.count > 2
          item_hash[:options] = item.third
        end

        item_hash
      else
        item
      end
    end

    render partial: 'shared/menu_button', locals: {
      title: title,
      button_class: button_class,
      items: menu_items
    }
  end
end

app/views/layouts/_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-51751300-1']);
  //_gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  _gaq.push(['_trackPageview']);
</script>

app/views/layouts/_categories_header.html.haml
%ul.categories-tabs.nav.nav-pills.col-md-8.col-sm-12

  - categories.each do |category|
    %li{class: ('active' if current_category?(category))}
      = link_to category.name, category, class: (category.hidden ? 'hidden-category' : '')
  - if admin_signed_in?
    %li
      %a{href: new_category_path}
        %strong New
.clearfix.visible-xs
%ul.nav.search-bar.col-md-4.col-sm-12
  = render 'layouts/search_field'
.clearfix

app/views/layouts/_flash_message.html.haml
%div{id: "flash_#{name}"}
  %div.alert.alert-dismissable{class: flash_class}
    %button{type: 'button', class: 'close', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'} &times;
    = msg

app/views/layouts/_footer.html.haml
%footer
  %a{href: 'mailto:yo@startupscriptures.com'}
    Talk to Moses
  |
  %a{href: 'mailto:yo@startupscriptures.com?content=Content suggestion'}
    Suggest Content

app/views/layouts/_log_in_menu.html.haml
- if user_signed_in?
  %li.dropdown.log-in-dropdown
    %a.dropdown-toggle(href='#' data-toggle="dropdown")
      = current_user.email
      - if current_user.is_admin
        (Admin)
      %b.caret
    %ul.dropdown-menu
      - if admin_signed_in?
        %li
          = link_to 'Import links', import_links_form_path
        %li.divider
        %li
          = link_to 'Recent links', recent_links_path
        %li
          = link_to 'Links without titles', links_without_titles_path
        - if admin_signed_in?
          %li.divider
          %li
            = link_to 'Background tasks dashboard', background_tasks_dashboard_path
        %li.divider
      %li
        = link_to 'Edit profile', edit_user_registration_path
      %li.divider
      %li
        = link_to 'Log out', destroy_user_session_path, method: :delete
- else
  %li
    = link_to 'Log in/Register', new_user_session_path, class: ''

app/views/layouts/_navbar.html.haml
.main-header
  %nav.navbar.navbar-default.header-bar{role: 'navigation'}
    .container-fluid
      .navbar-header
        %span.beta-sign
          Beta
        %a{href: root_path}
          %img.navbar-logo{src: image_path('logo.png')}
        .visible-xs
          .image-spacer-hack
      .header-wrapper
        #main-navbar-collapse
          %ul.nav.navbar-nav.navbar-right.navbar.header-buttons
            - if user_signed_in?
              %li
                %a{href: root_path} My Dashboard
              %li
                %a{href: reading_list_path} Reading List
            = render 'layouts/log_in_menu'

app/views/layouts/_search_field.html.haml
%form.navbar-form.navbar-right.search-field{role: 'search', action: links_search_path, method: 'get'}
  .form-group
    %input.form-control{type: 'text', placeholder: 'Search', name: 'q'}
  %button.btn.btn-default{type: 'submit'} Search

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= (content_for?(:title) ? "#{yield(:title)} - " : '') + 'Startup Scriptures'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = include_gon
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if content_for? :before_content
      = yield :before_content

    = flash_messages

    .container-fluid
      = yield :container_content

    - if content_for? :after_content
      = yield :after_content
    - if Rails.env.production?
      = render partial: 'layouts/analytics'

app/views/layouts/devise.html.haml
- content_for :before_content do
  = render 'layouts/navbar'

- content_for :container_content do
  .col-md-8
    = yield

= render template: 'layouts/application'

app/views/layouts/with_categories_header.html.haml
- content_for :before_content do
  = render 'layouts/navbar'
  = render 'layouts/categories_header'

- content_for :container_content do
  = yield

- content_for :after_content do
  = render partial: 'layouts/footer'

= render template: 'layouts/application'

app/views/layouts/with_header.html.haml
- content_for :before_content do
  = render 'layouts/categories_header'

- content_for :container_content do
  = yield

= render template: 'layouts/application'